apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.fullname" . }}-statamic-ssh
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: statamic
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "4"
data:
  id_key: {{ .Values.statamic.repo.sshPrivateKey | b64enc | quote }}
  known_hosts: {{ .Values.statamic.repo.knownHosts | b64enc | quote }}
