apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.fullname" . }}-statamic-ssh
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: statamic
data:
  id_rsa: {{ .Values.statamic.repo.sshPrivateKey | b64enc | quote }}
  known_hosts: {{ .Values.statamic.repo.knownHosts | b64enc | quote }}
