repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
    exclude_types: ['markdown']
  - id: trailing-whitespace
    exclude_types: ['markdown']
  - id: mixed-line-ending
  - id: fix-byte-order-marker
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.2
  hooks:
  - id: gitleaks
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.4.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
