{{- if .Values.reverb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.fullname" . }}-reverb
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: reverb
spec:
  {{- if not .Values.reverb.autoscaling.enabled }}
  replicas: {{ .Values.reverb.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.reverb.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: reverb
  strategy:
    {{- toYaml .Values.reverb.strategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-envs.yaml") . | sha256sum }}
        checksum/meilisearch-key: {{ include (print $.Template.BasePath "/meilisearch-masterkey-secret.yaml") . | sha256sum }}
        {{- with .Values.reverb.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "laravel-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: reverb
        app.kubernetes.io/part-of: laravel-app
    spec:
      {{- include "laravel-app.podSpec" (dict "ctx" . "component" "reverb" "values" .Values.reverb) | nindent 6 }}
{{- end }}
