{{- if and .Values.reverb.enabled .Values.reverb.ingress.enabled }}
{{- $fullName := include "laravel-app.fullname" . -}}
{{- $servicePort := .Values.reverb.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-reverb
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: reverb
  {{- with .Values.reverb.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.reverb.ingress.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.reverb.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.reverb.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-reverb
                port:
                  number: {{ $servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
