{{- if default true .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.fullname" . }}-webapp
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.app.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webapp
  strategy:
    {{- toYaml .Values.app.strategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-envs.yaml") . | sha256sum }}
        checksum/meilisearch-key: {{ include (print $.Template.BasePath "/meilisearch-masterkey-secret.yaml") . | sha256sum }}
        {{- if .Values.statamic.enabled }}
        checksum/statamic-init: {{ include (print $.Template.BasePath "/init-script.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.app.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "laravel-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: webapp
        app.kubernetes.io/part-of: laravel-app
    spec:
      {{- include "laravel-app.podSpec" (dict "ctx" . "component" "app" "values" .Values.app) | nindent 6 }}
{{- end }}
