{{- if .Values.app.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "laravel-app.fullname" . }}-app-service-monitor
  namespace: {{ .Values.app.serviceMonitor.namespace }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: http
    scheme: http
  jobLabel: app
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
{{- end }}
