# namespace:

image: hetznercloud/hcloud-csi-driver
tag: 2.2.0
imagePullPolicy: IfNotPresent
controller:
  attacher:
    image: registry.k8s.io/sig-storage/csi-attacher
    tag: v4.1.0
  resizer:
    image: registry.k8s.io/sig-storage/csi-resizer
    tag: v1.7.0
  provisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner
    tag: v3.4.0
  livenessprobe:
    image: registry.k8s.io/sig-storage/livenessprobe
    tag: v2.9.0

node:
  kubeletPath: /var/lib/kubelet
  registrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: v2.4.0
  livenessprobe:
    image: registry.k8s.io/sig-storage/livenessprobe
    tag: v2.9.0

storageClass:
  name: hcloud-volume
  isDefault: false
  reclaimPolicy: "Retain"

secret:
  # hcloudApiToken:
  existingSecretName: hcloud
  tokenKey: token

metrics:
  enabled: false
