apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.fullname" . }}-webapp
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
  # scale via ui or cli. this can not be here as it will overwrite the current replica count
  #  replicas: 3
#   minReadySeconds: 5
#   revisionHistoryLimit: 1
  strategy:
    {{- toYaml .Values.app.strategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "laravel-app.serviceAccountName" . }}
      {{- end }}
      initContainers:
        - name: artisan
          args:
            - /bin/bash
            - -c
            - php artisan optimize
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          envFrom:
            {{- if .Values.envSecretName }}
            - secretRef:
                name: {{ .Values.envSecretName }}
            {{- end }}
            {{- if .Values.envConfigMapName }}
            - configMapRef:
                name: {{ .Values.envConfigMapName }}
            {{- end }}
          env:
            - name: SSL_MODE
              value: off
        - name: migrate
          args:
            - /bin/bash
            - -c
            - php artisan migrate --force
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "Always" }}
          envFrom:
            {{- if .Values.envSecretName }}
            - secretRef:
                name: {{ .Values.envSecretName }}
            {{- end }}
            {{- if .Values.envConfigMapName }}
            - configMapRef:
                name: {{ .Values.envConfigMapName }}
            {{- end }}
          env:
            - name: SSL_MODE
              value: off
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          envFrom:
            {{- if .Values.envSecretName }}
            - secretRef:
                name: {{ .Values.envSecretName }}
            {{- end }}
            {{- if .Values.envConfigMapName }}
            - configMapRef:
                name: {{ .Values.envConfigMapName }}
            {{- end }}
          env:
            - name: SSL_MODE
              value: off
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.app.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.app.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
#          volumeMounts:
#            - mountPath: /var/www
#              name: codebase
#      volumes:
#        - emptyDir: {}
#          name: codebase
