apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel-app.fullname" . }}-init-script
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
data:
  init.sh: |-
    #!/bin/bash

    # Declare an associative array with the source as the key and destination as the value
    declare -A links=(
        ["/var/www/html/content/"]="/data/git/content/"
        ["/var/www/html/users/"]="/data/git/users/"
        ["/var/www/html/resources/blueprints/"]="/data/git/resources/blueprints/"
        ["/var/www/html/resources/fieldsets/"]="/data/git/resources/fieldsets/"
        ["/var/www/html/resources/forms/"]="/data/git/resources/forms/"
        ["/var/www/html/resources/users/"]="/data/git/resources/users/"
        ["/var/www/html/resources/preferences.yaml"]="/data/git/resources/preferences.yaml"
        ["/var/www/html/storage/forms/"]="/data/git/storage/forms/"
    )
    ​
    # Loop through the associative array and create the symbolic links
    for source in "${!links[@]}"; do
        destination=${links[$source]}
        if [ -e "$source" ] && [ ! -e "$destination" ]; then
            ln -s "$source" "$destination"
            echo "Linked $source to $destination"
        else
            echo "Failed to link $source to $destination. Ensure source exists and destination doesn't."
        fi
    done
    # PHP Init
    php artisan optimize && php artisan view:cache