{{- if and  .Values.meilisearch.enabled .Values.meiliMasterKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.meiliMasterKeySecretName}}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
stringData:
  MEILI_MASTER_KEY:  {{ .Values.meiliMasterKey | quote }}
{{- end }}
