{{- if and .Values.meilisearch.enabled .Values.meiliMasterKey (not .Values.meiliMasterKeyExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.meilisearchSecretName" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
stringData:
  MEILI_MASTER_KEY: {{ .Values.meiliMasterKey | quote }}
{{- end }}
