{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "laravel-app.fullname" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 8 }}
      podSelector:
        {{- toYaml .Values.networkPolicy.ingress.podSelector | nindent 8 }}
    ports:
    - protocol: TCP
      port: {{ ternary .Values.app.octane.port .Values.app.service.targetPort .Values.app.octane.enabled }}
    {{- if .Values.reverb.enabled }}
    - protocol: TCP
      port: {{ .Values.reverb.service.targetPort }}
    {{- end }}
  egress:
  # Kubernetes DNS.
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  {{- if .Values.valkey.enabled }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: valkey
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 6379
  {{- end }}
  {{- with .Values.networkPolicy.egress.additionalRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
