apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-config
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.envs }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
