{{- if .Values.queue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.fullname" . }}-queue
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: queue
spec:
  {{- if not .Values.queue.autoscaling.enabled }}
  replicas: {{ .Values.queue.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.queue.strategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.queue.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-envs.yaml") . | sha256sum }}
        checksum/meilisearch-key: {{ include (print $.Template.BasePath "/meilisearch-masterkey-secret.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: queue
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "laravel-app.serviceAccountName" . }}
      {{- end }}

      volumes:
      - name: runtime-cache
        emptyDir:
          sizeLimit: 1Mi
      {{- if .Values.statamic.enabled }}
      - name: data
        emptyDir: {}
      - name: statamic
        persistentVolumeClaim:
          claimName: {{ include "laravel-app.fullname" . }}-statamic-pvc
      - name: init-script
        configMap:
          defaultMode: 448
          name: {{ include "laravel-app.fullname" . }}-init-script
      {{- end }}
      {{- with .Values.queue.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

      initContainers:
        - name: init
          args:
            - /bin/bash
            - -c
            - php artisan optimize && php artisan view:cache
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.queue.image.repository }}:{{ .Values.queue.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.queue.image.pullPolicy }}
          volumeMounts:
          - name: runtime-cache
            mountPath: /var/www/html/bootstrap/cache
          {{- if .Values.statamic.enabled }}
          - name: statamic
            mountPath: /data/git
          - name: data
            mountPath: /data
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "laravel-app.fullname" . }}-config
          {{- if and .Values.meilisearch.enabled .Values.meiliMasterKey }}
          env:
          - name: MEILISEARCH_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.meiliMasterKeySecretName }}
                key: MEILI_MASTER_KEY
          {{- end }}
      containers:
        - name: queue
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.queue.image.repository }}:{{ .Values.queue.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.queue.image.pullPolicy }}
          volumeMounts:
          - name: runtime-cache
            mountPath: /var/www/html/bootstrap/cache
          {{- if .Values.statamic.enabled }}
          - name: statamic
            mountPath: /data/git
          - name: data
            mountPath: /data
          - name: init-script
            mountPath: /app/init.sh
            subPath: init.sh
            readOnly: true
          {{- end }}
          {{- with .Values.queue.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.statamic.enabled }}
          env:
          - name: STARTUP_SCRIPT_PATH
            value: /app/init.sh
          {{- end }}
          args:
            - /bin/bash
            - -c
            - php artisan horizon > /dev/null
          resources:
            {{- toYaml .Values.queue.resources | nindent 12 }}
      {{- with .Values.queue.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.affinity }}
      affinity:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
