{{- if .Values.queue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.fullname" . }}-queue
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: queue
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap-envs.yaml") . | sha256sum }}
spec:
  {{- if not .Values.queue.autoscaling.enabled }}
  replicas: {{ .Values.queue.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.queue.strategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.queue.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: queue
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "laravel-app.serviceAccountName" . }}
      {{- end }}

      volumes:
      - name: runtime-cache
        emptyDir:
          sizeLimit: 1Mi
      {{- with .Values.queue.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

      initContainers:
        - name: artisan
          args:
            - /bin/bash
            - -c
            - php artisan optimize && php artisan view:cache
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.queue.image.repository }}:{{ .Values.queue.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.queue.image.pullPolicy }}
          volumeMounts:
          - name: runtime-cache
            mountPath: /var/www/html/bootstrap/cache
          envFrom:
            {{- if .Values.envSecretName }}
            - secretRef:
                name: {{ .Values.envSecretName }}
            {{- end }}
            {{- if .Values.envConfigMapName }}
            - configMapRef:
                name: {{ .Values.envConfigMapName }}
            {{- end }}
            - configMapRef:
                name: {{ include "laravel-app.fullname" . }}-config
          env:
            - name: SSL_MODE
              value: off
      containers:
        - name: queue
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.queue.image.repository }}:{{ .Values.queue.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.queue.image.pullPolicy }}
          volumeMounts:
          - name: runtime-cache
            mountPath: /var/www/html/bootstrap/cache
          {{- with .Values.queue.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
            - name: SSL_MODE
              value: off
          args:
            - /bin/bash
            - -c
            - php artisan horizon > /dev/null
          resources:
            {{- toYaml .Values.queue.resources | nindent 12 }}
      {{- with .Values.queue.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.affinity }}
      affinity:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
