# Broad smoke-test configuration used by CI.
webRoot: /app

existingEnvSecrets:
- laravel-test-secrets

envs:
  APP_ENV: testing
  LOG_CHANNEL: stderr

statamic:
  enabled: true
  repo:
    existingSecret: statamic-test-ssh

app:
  image:
    tag: 8.5-frankenphp
  replicaCount: 2
  autoscaling:
    enabled: true
  podDisruptionBudget:
    enabled: true
  octane:
    enabled: true
  ingress:
    enabled: true

queue:
  enabled: true
  autoscaling:
    enabled: true
  podDisruptionBudget:
    enabled: true

reverb:
  enabled: true
  autoscaling:
    enabled: true
  podDisruptionBudget:
    enabled: true
  ingress:
    enabled: true

scheduler:
  enabled: true

networkPolicy:
  enabled: true
