{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.fullname" . }}-scheduler
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.scheduler.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-envs.yaml") . | sha256sum }}
        {{- if .Values.statamic.enabled }}
        checksum/statamic-init: {{ include (print $.Template.BasePath "/init-script.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.scheduler.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "laravel-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/part-of: laravel-app
    spec:
      {{- include "laravel-app.podSpec" (dict "ctx" . "component" "scheduler" "values" .Values.scheduler) | nindent 6 }}
{{- end }}
