{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.fullname" . }}-scheduler
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap-envs.yaml") . | sha256sum }}
    checksum/meilisearch-key: {{ include (print $.Template.BasePath "/meilisearch-masterkey-secret.yaml") . | sha256sum }}
spec:
  {{- if not .Values.scheduler.autoscaling.enabled }}
  replicas: {{ .Values.scheduler.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.scheduler.strategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.scheduler.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: scheduler
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "laravel-app.serviceAccountName" . }}
      {{- end }}
      
      volumes:
      - name: runtime-cache
        emptyDir:
          sizeLimit: 1Mi
      - name: data
        emptyDir: {}
      {{- if .Values.statamic.enabled }}
      - name: statamic
        persistentVolumeClaim:
          claimName: {{ include "laravel-app.fullname" . }}-statamic-pvc
      {{- end }}
      - name: init-script
        configMap:
          name: {{ include "laravel-app.fullname" . }}-init-script
      {{- with .Values.scheduler.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

      initContainers:
        - name: init
          args:
            - /bin/bash
            - -c
            - /app/init.sh
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          volumeMounts:
          - name: runtime-cache
            mountPath: /var/www/html/bootstrap/cache
          {{- if .Values.statamic.enabled }}
          - name: statamic
            mountPath: /data/git
          {{- end }}
          - name: init-script
            mountPath: /app/init.sh
            subPath: init.sh
            readOnly: true
          - name: data
            mountPath: /data
          envFrom:
            {{- if .Values.envSecretName }}
            - secretRef:
                name: {{ .Values.envSecretName }}
            {{- end }}
            {{- if .Values.envConfigMapName }}
            - configMapRef:
                name: {{ .Values.envConfigMapName }}
            {{- end }}
            - configMapRef:
                name: {{ include "laravel-app.fullname" . }}-config
          {{- if and .Values.meilisearch.enabled .Values.meiliMasterKey }}
          env:
          - name: MEILISEARCH_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.meiliMasterKeySecretName }}
                key: MEILI_MASTER_KEY
          {{- end }}
      containers:
        - name: scheduler
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          volumeMounts:
          - name: runtime-cache
            mountPath: /var/www/html/bootstrap/cache
          {{- if .Values.statamic.enabled }}
          - name: statamic
            mountPath: /data/git
          {{- end }}
          - name: data
            mountPath: /data
          {{- with .Values.scheduler.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          args:
            - /bin/bash
            - -c
            - php artisan schedule:work > /dev/null
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
