apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uptime-operator.staticMonitorsConfigMapName" . }}
  labels:
    {{- include "uptime-operator.labels" . | nindent 4 }}
data:
  monitors.yaml: |
    {{- if .Values.staticMonitors }}
    {{- dict "monitors" .Values.staticMonitors | toYaml | nindent 4 }}
    {{- else }}
    monitors: []
    {{- end }}
