apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptime-operator.fullname" . }}
  labels:
    {{- include "uptime-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "uptime-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/static-monitors: {{ include (print $.Template.BasePath "/configmap-static-monitors.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "uptime-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uptime-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "uptime-operator.configMapName" . }}
          env:
            - name: KUMA_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "uptime-operator.secretName" . }}
                  key: {{ .Values.existingSecretKeys.url | quote }}
            - name: KUMA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "uptime-operator.secretName" . }}
                  key: {{ .Values.existingSecretKeys.username | quote }}
            - name: KUMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uptime-operator.secretName" . }}
                  key: {{ .Values.existingSecretKeys.password | quote }}
            {{- if .Values.gomemlimit }}
            - name: GOMEMLIMIT
              value: {{ .Values.gomemlimit | quote }}
            {{- end }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: static-monitors
              mountPath: {{ .Values.config.staticMonitorsPath | dir | quote }}
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: static-monitors
          configMap:
            name: {{ include "uptime-operator.staticMonitorsConfigMapName" . }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
