{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-operator.secretName" . }}
  labels:
    {{- include "uptime-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecretKeys.url }}: {{ required "secret.url is required when secret.create is true" .Values.secret.url | quote }}
  {{ .Values.existingSecretKeys.username }}: {{ required "secret.username is required when secret.create is true" .Values.secret.username | quote }}
  {{ .Values.existingSecretKeys.password }}: {{ required "secret.password is required when secret.create is true" .Values.secret.password | quote }}
{{- end }}
