name: Release Charts

on:
  push:
    branches:
    - main
    paths:
    - 'charts/**'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        token: ${{ github.token }}

    - name: Add dependency chart repos
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add meilisearch https://meilisearch.github.io/meilisearch-kubernetes

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: ${{ github.token }}
        CR_SKIP_EXISTING: true
